import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    safeArea: {
    flex: 1,
    backgroundColor: '#f4f4f8',
  },
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#f4f4f8',
  },
  logo: {
    paddingTop: 50,
    width: 150,
    height: 30,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginRight: 8,
  },
  logoText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#013247',
  },
  greetingContainer: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  greetingTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#013247',
    fontFamily: 'Helvetica',
  },
  greetingSubtitle: {
    fontSize: 16,
    color: '#666',
    marginTop: 4,
    fontFamily: 'Helvetica',
  },
  actionGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  actionButton: {
    flex: 1, // Make buttons share space
    backgroundColor: '#50bcfc',
    borderRadius: 20,
    padding: 20,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    height: 160,
    marginHorizontal: 5,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  actionImage: {
    width: 60,
    height: 60,
    resizeMode: 'contain',
    position: 'absolute',
    bottom: 10,
    right: 10,
  },
  actionText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    width: '70%',
    fontFamily: 'Helvetica',
  },
  dailyThought: {
    backgroundColor: '#3a3a4c',
    borderRadius: 20,
    padding: 20,
    marginHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
  },
  dailyThoughtTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    fontFamily: 'Helvetica',
  },
  dailyThoughtSubtitle: {
    fontSize: 12,
    color: '#DDD',
    marginTop: 4,
  },
  playButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  playIcon: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderTopWidth: 8,
    borderBottomWidth: 8,
    borderLeftWidth: 14,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: '#FFFFFF',
    marginLeft: 4,
  },
  quickAccessContainer: {
    paddingHorizontal: 20,
  },
  quickAccessTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#013247',
    marginBottom: 10,
    fontFamily: 'Helvetica',
  },
  quickAccessItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  quickAccessIcon: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
    marginRight: 15,
  },
  quickAccessDetails: {
    flex: 1,
  },
  quickAccessName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000',
  },
  quickAccessDate: {
    fontSize: 12,
    color: '#666',
    marginTop: 4,
  },
  openButton: {
    backgroundColor: '#fdecec',
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  openButtonText: {
    color: '#dd5757',
    fontWeight: '600',
    fontSize: 12,
  },
});